[project]
name = "state-of-the-delta"
version = "0.1.0"
description = "State of the Delta"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deltaeo>=2026.7.6",
    "dllmforge[api]",
    "dotenv>=0.9.9",
    "markdown>=3.10.3",
    "matplotlib-map-utils>=4.1.1",
    "openai>=2.54.0",
    "resplotlib>=0.0.1",
]

[tool.uv.sources]
resplotlib = { git = "https://github.com/Ruben-White/resplotlib.git", rev = "main" }
deltaeo = { git = "https://github.com/Deltares-research/deltaeo.git", rev = "reloaded" }
dllmforge = { git = "https://github.com/Deltares-research/DLLMForge.git" }

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
